### ISSUE TITLE
Keeping DocPad Plugins up to date

### ISSUE THREAD

**Issue by balupton** [bevry-archive/meta#27]
Hey @docpad/extras-team

I need your help in keeping plugin dependencies up to date.

First we will need to setup a development copy of DocPad:

```
cd ~
git clone https://github.com/docpad/docpad.git
cd docpad
npm install
cake compile
npm link
```

Then we can setup the extras project:

```
cd ~
git clone https://github.com/docpad/extras.git docpad-extras
cd docpad-extras
npm install
npm link docpad
./app clone
```

Then we can find out which plugin deps are out of date by running:

```
./app outdated
```

It will then produce output like:

```
info: /Users/balupton/Projects/docpad-extras/plugins/browserifydocs
browserify has 9.0.3, but ^4.1.4 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/highlightjs
bal-util has 2.5.1, but ~2.4.1 is specified
highlight.js has 8.4.0, but ~8.3.0 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/downloader
tar has 1.0.3, but ~0.1.19 is specified
hyperquest has 1.0.1, but ~0.2.0 is specified
taskgroup has 4.2.1, but ~3.3.6 is specified
rimraf has 2.3.1, but ~2.2.5 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/cleancss
clean-css has 3.1.4, but ~2.0.2 is specified
taskgroup has 4.2.1, but ~3.3.6 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/livereload
primus has 2.4.12, but ~2.0.0 is specified
ws has 0.7.1, but ~0.4.31 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/multiplelayouts
taskgroup has 4.2.1, but ~3.4.0 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/less
less has 2.4.0, but ~1.6.0 is specified

info: /Users/balupton/Projects/docpad-extras/plugins/nativecomments
rimraf has 2.3.1, but ~2.2.2 is specified
chai has 2.1.1, but ~1.7.2 is specified
superagent has 0.21.0, but ~0.15.4 is specified
```

Which can be acted upon. Ideally we will have people familiar with the particular plugin they are updating - as that way they can further ensure that the updated dependency won't break anything.

**Comment by mikeumus** [comment]
Roger that.

**Comment by balupton** [comment]
I'll take any that need taskgroup updated.

**Comment by greduan** [comment]
We could also automate this process if we find or make the right tools :)

**Comment by mikeumus** [comment]
Good idea, but for now it needs to get done.

**Comment by mikeumus** [comment]
getting this:

```
(precise)mikeumus@localhost:~/Downloads/Bevry/DocPad/Dev/docpad$ cake compile
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /home/mikeumus/Downloads/Bevry/DocPad/Dev/docpad/node_modules/.bin/coffee ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

:blush:

**Comment by balupton** [comment]
Moved to https://discuss.bevry.me/t/keeping-docpad-plugins-updated/34
